[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "tests"
solc_version = "0.8.20"

[fmt]
width = 120
tab_width = 2

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
gnosis = "${GNOSIS_CHAIN_RPC_URL}"

[etherscan]
gnosis = { key = "${GNOSIS_CHAIN_SCAN_API_KEY}", url = "${GNOSIS_CHAIN_ETHERSCAN_VERIFIER_URL}" }