name: Publish SDK to GitHub Packages
on:
  push:
    branches: ['main', 'development']
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: pnpm/action-setup@v4
      - run: pnpm i
      - run: cd packages/sdk && sh ./publish.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}